version: '3.8'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 5
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - wp_network
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
    volumes:
      - wp_data:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - wp_network
    restart: always
    
  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
    env_file:
      - ./.env
    volumes:
      - wp_data:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    ports: 
      - "9000:9000"
    networks:
      - wp_network
    restart: always

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/khadj-me/data/db_data
      o: bind
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/khadj-me/data/wp_data
      o: bind


networks:
  wp_network:
    driver: bridge
