version: '3.8'

services:
  db:
    build:
      context: ./requirements/mariadb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 5
    env_file:
      - ./.env
    volumes:
      - /home/khadj-me/data/db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - wp_network
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
    volumes:
      - /home/khadj-me/data/wp_data:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wp
    networks:
      - wp_network
    restart: always
    
  wp:
    build:
      context: ./requirements/wordpress
    env_file:
      - ./.env
    volumes:
      - /home/khadj-me/data/wp_data:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    ports: 
      - "9000:9000"
    networks:
      - wp_network
    restart: always

networks:
  wp_network:
