services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 5
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - wp_network
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    volumes:
      - wp_data:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - wp_network
    restart: always
    
  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    env_file:
      - ./.env
    volumes:
      - wp_data:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    expose: 
      - "9000"
    networks:
      - wp_network
    restart: always

networks:
  wp_network:
    driver: bridge

volumes:
  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      type: none
      device: /home/khadj-me/data/wp_data
      o: bind
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      device: /home/khadj-me/data/db_data
      o: bind