version: '3.8'

services:
  db:
    build:
      context: ./mariadb
    env_file:
      - ./.env
    volumes:
      - /home/khadj-me/data/db_data:/var/lib/mysql
    networks:
      - wp_network
    expose:
      - "3306"
    restart: always

  nginx:
    build:
      context: ./nginx
    volumes:
      - /home/khadj-me/data/wp_data:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wp
    networks:
      - wp_network
    restart: always
    
  wp:
    build:
      context: ./wordpress
    env_file:
      - ./.env
    volumes:
      - /home/khadj-me/data/wp_data:/var/www/html
    depends_on:
      - db
    ports: 
      - "9000:9000"
    networks:
      - wp_network
    restart: always

networks:
  wp_network:
