version: '3.8'

services:
  db:
    build:
      context: ./mariadb
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network
    expose:
      - "3306"
    restart: always

  nginx:
    build:
      context: ./nginx
    volumes:
      - wp_data:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - wp
    networks:
      - wp_network
    restart: always
  wp:
    build:
      context: ./wordpress
    env_file:
      - ./.env
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - db
    ports: 
      - "9000:9000"
    networks:
      - wp_network
    restart: always

volumes:
  db_data:
  wp_data:

networks:
  wp_network:
